services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web 