version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_USER_DB_ID=${NOTION_USER_DB_ID}
      - GLOBAL_FILE_INDEX_DB_ID=${GLOBAL_FILE_INDEX_DB_ID}
      - SECRET_KEY=${SECRET_KEY}
    restart: always 