from typing import BinaryIO

from cryptography.fernet import Fernet


def generate_key() -> bytes:
    """Generate a new symmetric key for encryption."""
    return Fernet.generate_key()


def encrypt_stream(key: bytes, stream: BinaryIO) -> bytes:
    """Encrypt data from a binary stream using the provided key.

    Parameters
    ----------
    key: bytes
        Symmetric key generated by :func:`generate_key`.
    stream: BinaryIO
        Stream providing plaintext bytes.

    Returns
    -------
    bytes
        Encrypted ciphertext.
    """
    fernet = Fernet(key)
    data = stream.read()
    return fernet.encrypt(data)


def decrypt_stream(key: bytes, stream: BinaryIO) -> bytes:
    """Decrypt data from a binary stream using the provided key.

    Parameters
    ----------
    key: bytes
        Symmetric key generated by :func:`generate_key`.
    stream: BinaryIO
        Stream providing ciphertext bytes.

    Returns
    -------
    bytes
        Decrypted plaintext.
    """
    fernet = Fernet(key)
    data = stream.read()
    return fernet.decrypt(data)
